---
title: HubOfMachineLearning
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: Hub of Machine Learning
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/default-social-image.png"
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: hubofml
author: hubofml
social:
  name: HubOfMachineLearning
  links:
  - https://twitter.com/hubofml
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
lang: en-GB
logo: "/assets/logos/logo.png"
description: A one-stop place to find high-quality resources on machine learning, computer vision and data science
url: https://hubofml.github.io
baseurl: 
repo: https://github.com/hubofml/hubofml.github.io
email: hubofml@gmail.com
css_inline: true
favicons:
  '16': "/assets/logos/logo@16px.png"
  '32': "/assets/logos/logo@32px.png"
  '96': "/assets/logos/logo@96px.png"
  '120': "/assets/logos/logo@120px.png"
  '144': "/assets/logos/logo@144px.png"
  '180': "/assets/logos/logo@180px.png"
  '512': "/assets/logos/logo@512px.png"
  '1024': "/assets/logos/logo@1024px.png"
navigation_header:
- title: Home
  url: "/"
- title: Newsletter
  url: "/newsletter"
- title: About
  url: "/about/"
navigation_footer:
- title: Created by Samuel
  url: https://hubofco.de
social_links:
  Twitter: https://twitter.com/hubofml
sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
